#!/bin/bash

docker_cli_plugin_metadata() {
local vendor="arlechann"
local url="https://github.com/arlechann/shellutils"
local description="Print selected docker image id"
local version="0.0.1"
cat <<-EOF
{"SchemaVersion":"0.1.0","Vendor":"${vendor}","Version":"${version}","ShortDescription":"${description}","URL":"${url}"}
EOF
}

fimages() {
	local images=$(sudo docker images)
	echo "$images" | fzf --header-lines=1 -m | awk '$0=$3'
}

case "$1" in
	docker-cli-plugin-metadata)
		docker_cli_plugin_metadata
		;;
  *)
	fimages $@
	;;
esac
