#!/bin/bash

docker_cli_plugin_metadata() {
local vendor="arlechann"
local url="https://github.com/arlechann/shellutils"
local description="Attach selected container"
local version="0.0.1"
cat <<-EOF
{"SchemaVersion":"0.1.0","Vendor":"${vendor}","Version":"${version}","ShortDescription":"${description}","URL":"${url}"}
EOF
}

fexec() {
	local pss=$(sudo docker ps -a)
	echo "$pss" | fzf --header-lines=1 | awk '$0=$1' | xargs -ro -I{} sudo docker exec -it {} "${2:-/bin/bash}"
}

case "$1" in
	docker-cli-plugin-metadata)
		docker_cli_plugin_metadata
		;;
	*)
		fexec
		;;
esac
